In [1]:
### Assessment

#1) Create a null vector of size 10
#2) Create a null vector of size 10 but the fifth value should be one
#3) Create a vector with values ranging from 10 to 65
#4) Reverse the above vector
#5) Create a 3x3 matrix with values ranging from 0 to 8


# 1) Create a null vector of size 10

In [2]:
import numpy as np

In [3]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 2) Create a null vector of size 10 but the fifth value should be one

In [4]:
x=np.zeros(10)
print(x)
x[7]=1
x

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

# 3) Create a vector with values ranging from 10 to 65

In [5]:
value=np.arange(10,65)
print(value)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64]


# 4) Reverse the above vector

In [6]:
value=value[::-1]
value

array([64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48,
       47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31,
       30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
       13, 12, 11, 10])

In [7]:
value=value[1:5]
value

array([63, 62, 61, 60])

# 5) Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
matrix=np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])